config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :photos
  resources :racers
  resources :slogans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'site/home'
  root to: 'slogans#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/racer.rb
class Racer < ApplicationRecord
    has_one_attached :avatar
end

app/models/slogan.rb
class Slogan < ApplicationRecord
    validates_presence_of :first_name
    validates_presence_of :last_name
    validates :email, presence: true, uniqueness: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

    validates :slogan, presence: true, length: {maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.fetch(:photo, {})
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/controllers/racers_controller.rb
class RacersController < ApplicationController
  before_action :set_racer, only: [:show, :edit, :update, :destroy]

  # GET /racers
  # GET /racers.json
  def index
    @racers = Racer.all
  end

  # GET /racers/1
  # GET /racers/1.json
  def show
    @racer = Racer.find(params[:id])
    
  end

  # GET /racers/new
  def new
    @racer = Racer.new
  end

  # GET /racers/1/edit
  def edit
  end

  # POST /racers
  # POST /racers.json
  def create
    @racer = Racer.new(racer_params)
        # racer.selfie.attach(params[:selfie])
      #  redirect_to @racer

    respond_to do |format|
      if @racer.save
        format.html { redirect_to @racer, notice: 'Racer was successfully created.' }
        format.json { render :show, status: :created, location: @racer }
      else
        format.html { render :new }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /racers/1
  # PATCH/PUT /racers/1.json
  def update
    respond_to do |format|
      if @racer.update(racer_params)
        format.html { redirect_to @racer, notice: 'Racer was successfully updated.' }
        format.json { render :show, status: :ok, location: @racer }
      else
        format.html { render :edit }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racers/1
  # DELETE /racers/1.json
  def destroy
    @racer.destroy
    respond_to do |format|
      format.html { redirect_to racers_url, notice: 'Racer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_racer
      @racer = Racer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def racer_params
      params.require(:racer).permit(:first_name, :last_name, :city, :state, :avatar)
    end
end

app/controllers/slogans_controller.rb
class SlogansController < ApplicationController
  before_action :set_slogan, only: [:show, :edit, :update, :destroy]

  # GET /slogans
  # GET /slogans.json
  def index
    @slogans = Slogan.all
  end

  # GET /slogans/1
  # GET /slogans/1.json
  def show
  end

  # GET /slogans/new
  def new
    @slogan = Slogan.new
  end

  # GET /slogans/1/edit
  def edit
  end

  # POST /slogans
  # POST /slogans.json
  def create
    @slogan = Slogan.new(slogan_params)

    respond_to do |format|
      if @slogan.save
        format.html { redirect_to @slogan, notice: 'Slogan was successfully created.' }
        format.json { render :show, status: :created, location: @slogan }
      else
        format.html { render :new }
        format.json { render json: @slogan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slogans/1
  # PATCH/PUT /slogans/1.json
  def update
    respond_to do |format|
      if @slogan.update(slogan_params)
        format.html { redirect_to @slogan, notice: 'Slogan was successfully updated.' }
        format.json { render :show, status: :ok, location: @slogan }
      else
        format.html { render :edit }
        format.json { render json: @slogan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slogans/1
  # DELETE /slogans/1.json
  def destroy
    @slogan.destroy
    respond_to do |format|
      format.html { redirect_to slogans_url, notice: 'Slogan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slogan
      @slogan = Slogan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slogan_params
      params.require(:slogan).permit(:first_name, :last_name, :email, :slogan)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/racers_helper.rb
module RacersHelper
end

app/helpers/slogans_helper.rb
module SlogansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoulderBike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBxBnLuUfUKqSxV502zf-e4Op_o1rsAAoI' %>

<link href="application.css" rel="stylesheet" >

<link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Aclonica" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">

<title>BBR</title>

  </head>

  <body>

<div id='main_wrap'>
<div class='row'>
<header id='nav_bar'>
    <nav>
        <ul>
        <li><%= link_to 'Home', slogans_url %></li>
        <li><%= link_to 'Racers', racers_url %></li>
        <li><%= link_to 'Places', places_url %></li>
        <li><%= link_to 'Photos', photos_url %></li>
        <li><%= link_to 'Contest', slogans_url %></li>
        </ul>
    </nav>
</header>
 </div>

<div class='row'>
<div class='col-9'>
<div id='slogan'>
  <h1>Your Slogan Here</h1>
  <%= link_to "Enter Now", new_slogan_path %>
</div>
</div>


<div class='col-3'>
<div id='logo'>
    <%= image_tag("flatiron.png", :alt => "Irons") %>
</div>


<div id='banner_top'>
    <h1>Boudler</h1>
</div>

<div id='banner_bttm'>
    <h1>Bike Race</h1>
    <h1>2020</h1>
</div>
</div>
</div>

<div class='row'>
<div id="countdown">
  <h2 id="demo"></h2>
  <script>
  var countDownDate = new Date("April 1, 2020 07:00:00").getTime();
  var x = setInterval(function() {

  var now = new Date().getTime();

  var distance = countDownDate - now;

  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";

  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
  }, 1000);
  </script>
</div>
</div>

<div class='row'>
    <%= yield %>
</div>

<div class='row'>
<div id= 'footer'>
  <footer>
    <ul>
    <li><a href="#">Twitter</a></li>
    <li><a href="#">Facebook</a></li>
    <li><a href="#">Instagram</a></li>
    <li><a href="#">Flickr</a></li>
    <li><a href="#">GoogleMaps</a></li>
    </ul>
    </footer>
</div>
</div>
</div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>
<div id='photos' class='layer'></div>
<script>
var current_page=1;
fetch_data(current_page)
</script>

<div id='buttons'>
<button onclick="next()">Next</button>
<button onclick="back()">Previous</button>
</div>

# <%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>


<div id="map"></div>
<script>InitMap()</script>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>


<div id="map"></div>
<script>InitMap()</script>

app/views/racers/_form.html.erb
<%= form_with(model: racer, local: true) do |form| %>
  <% if racer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(racer.errors.count, "error") %> prohibited this racer from being saved:</h2>

      <ul>
      <% racer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
        <%=form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/racers/edit.html.erb
<h1>Editing Racer</h1>

<%= render 'form', racer: @racer %>

<%= link_to 'Show', @racer %> |
<%= link_to 'Back', racers_path %>

app/views/racers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Racers</h1>

<div class='wrapper'>
<div class='row'>
  <div class='racer_box'>
    <div class='profile'>
    <%= image_tag('A.jpg', :style => "height: 100px; width: 100px;") %>
    </div>
    <h1>Dustin Green</h1>
    <p>Hickory Hills, IL</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('B.jpg', :style => "height: 100px; width: 100px;") %>
  </div>   
    <h1>Jason Finn</h1>
    <p>Huntington Beach, CA</p> 
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('C.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Howard Thompson</h1>
    <p>Hale, MO</p>
  </div>
  </div>
  
  <div class='row'>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('D.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Maggie Lantz</h1>
    <p>Dublin, OH</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('E.jpg', :style => "height: 100px; width: 100px;") %>    
   </div> 
    <h1>Lawrence Duran</h1>
    <p>Fort Myers, FL</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('F.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Irene Molina</h1>
    <p>Tucson, AZ</p>
  </div>
  </div>
  
  <div class='row'>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('G.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>  
    <h1>Nancy Garner</h1>
    <p>Baltimore, MD</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('H.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Tara Taylor</h1>
    <p>Minneapolis, MN</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('I.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>  
    <h1>Alejandro Smith</h1>
    <p>Scarborough, ME</p>
  </div>
  </div>
  
  <div class='row'>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('J.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>  
    <h1>Tricia Renshaw</h1>
    <p>Mystic, CT</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('K.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Travis Cook</h1>
    <p>Twin Lakes, WI</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('L.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Joan Brooks</h1>
    <p>Norfolk, VA</p>
  </div>
  </div>
  
  <div class='row'>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('M.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Joseph Rodgers</h1>
    <p>Wayne, NJ</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('N.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Matthew Gregson</h1>
    <p>Brashear, MO</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('O.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>  
    <h1>Katie Dunlap</h1>
    <p>Marion, VA</p>
  </div>
  </div>
  
  <div class='row'>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('P.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Leo Howard</h1>
    <p>Dallas, TX</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('Q.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Maria Baisden</h1>
    <p>Raleigh, NC</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('R.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>
    <h1>Sandy Townsend</h1>
    <p>Newport, PA</p>
  </div>
  </div>

  <div class='row'>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('S.jpg', :style => "height: 100px; width: 100px;") %>    
  </div>  
    <h1>Melinda Stephenson</h1>
    <p>Kahului, HI</p>
  </div>
  <div class='racer_box'>
  <div class='profile'>
    <%= image_tag('T.jpg', :style => "height: 100px; width: 100px;") %>     
  </div>  
    <h1>Jason Nichols</h1>
    <p>Alexandria, VA</p>
  </div>
  </div>
</div>

# <%= link_to 'New Racer', new_racer_path %>

app/views/racers/new.html.erb
<h1>New Racer</h1>

<%= render 'form', racer: @racer %>

<%= link_to 'Back', racers_path %>

app/views/racers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>First name:</strong>
  <%= @racer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @racer.last_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @racer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @racer.state %>
</p>
</div>

<% if @racer.avatar.attached? %>
<div class='selfie'>
  <%= image_tag @racer.avatar %>
</div>
<%end%>

<%= link_to 'Edit', edit_racer_path(@racer) %> |
<%= link_to 'Back', racers_path %>

app/views/slogans/_form.html.erb
<%= form_with(model: slogan, local: true) do |form| %>
  <% if slogan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slogan.errors.count, "error") %> prohibited this slogan from being saved:</h2>

      <ul>
      <% slogan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :slogan %>
    <%= form.text_field :slogan %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slogans/edit.html.erb
<h1>Editing Slogan</h1>

<%= render 'form', slogan: @slogan %>

<%= link_to 'Show', @slogan %> |
<%= link_to 'Back', slogans_path %>

app/views/slogans/index.html.erb
<p id="notice"><%= notice %></p>

<div class='contest'>
<div class='row'>
<h1>Enter <%= link_to 'Here', new_slogan_path %> For Your Chance To Have Your Slogan Chosen For</h1><br>
<h1>The 2020 Dicennial Boulder Bike Race!</h1>
</div>
</div>


  <tbody>
    <% @slogans.each do |slogan| %>
      <tr>
        <td><%= slogan.first_name %></td>
        <td><%= slogan.last_name %></td>
        <td><%= slogan.email %></td>
        <td><%= slogan.slogan %></td>
       # <td><%= link_to 'Show', slogan %></td>
       # <td><%= link_to 'Edit', edit_slogan_path(slogan) %></td>
       # <td><%= link_to 'Destroy', slogan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

#<%= link_to 'New Slogan', new_slogan_path %>

app/views/slogans/new.html.erb
<%= render 'form', slogan: @slogan %>

<%= link_to 'Back', slogans_path %>

app/views/slogans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @slogan.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @slogan.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @slogan.email %>
</p>

<p>
  <strong>Slogan:</strong>
  <%= @slogan.slogan %>
</p>

<%= link_to 'Edit', edit_slogan_path(@slogan) %> |
<%= link_to 'Back', slogans_path %>